version: "3.7"
services:
  app:
    build:
      args:
        user: test
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: cloudvest
    container_name: cloudvest-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - cloudvest

  db:
    image: mysql:5.7
    container_name: cloudvest-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: "docker_test"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_PASSWORD: "root"
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - cloudvest

  nginx:
    image: nginx:alpine
    container_name: cloudvest-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - cloudvest

networks:
  cloudvest:
    driver: bridge
